LukeVo.Faith.MainWebsite/Models/BibleGatewayApi/BibleGatewayConnector.cs
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LukeVo.Faith.MainWebsite.Models.BibleGatewayApi
{

    public class BibleGatewayConnector
    {
        private const int ApiLifetime = 43200;

        private const string ServerEndpoint = "https://www.biblegateway.com/";
        private const string VotDEndpoint = "votd/get/?format=json&version={0}";

        private RestClient RestClient = new RestClient(ServerEndpoint);

        private CachableApi<string, VotDResponse> VotDCache = new CachableApi<string, VotDResponse>(ApiLifetime);

        public BibleGatewayConnector() { }
        
        public async Task<VotDResponse> GetVotDAsync(string version)
        {
            return await this.VotDCache.GetOrRequestAsync(version, async () =>
            {
                var request = new RestRequest(string.Format(VotDEndpoint, version), Method.GET);

                var response = await this.RestClient.ExecuteTaskAsync(request);
                var result = JsonConvert.DeserializeObject<VotDResponse>(response.Content);

                if (result.votd == null)
                {
                    throw new ArgumentException("Unknown version");
                }

                return result;
            });
        }

    }

}

LukeVo.Faith.MainWebsite/Models/BibleGatewayApi/BibleGatewayModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LukeVo.Faith.MainWebsite.Models.BibleGatewayApi
{
    public class VotD
    {
        public string text { get; set; }
        public string content { get; set; }
        public string display_ref { get; set; }
        public string reference { get; set; }
        public string permalink { get; set; }
        public string copyright { get; set; }
        public string copyrightlink { get; set; }
        public string audiolink { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string version { get; set; }
        public string version_id { get; set; }
    }

    public class VotDResponse
    {
        public VotD votd { get; set; }
    }
}

LukeVo.Faith.MainWebsite/Models/CachableApi.cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LukeVo.Faith.MainWebsite.Models
{
    public class CachableApi<TKey, TResult>
    {

        protected ConcurrentDictionary<TKey, CachableApiResult<TResult>> Cache { get; set; } = new ConcurrentDictionary<TKey, Models.CachableApiResult<TResult>>();
        public int ResultLifeTime { get; set; }

        public CachableApi(int resultLifeTime)
        {
            this.ResultLifeTime = resultLifeTime;
        }

        public TResult GetOrRequest(TKey key, Func<TResult> request)
        {
            if (Cache.TryGetValue(key, out var result) && !result.Expired(this.ResultLifeTime))
            {
                // Do nothing, use the cache
            }
            else
            {
                var freshResult = request();
                result = new CachableApiResult<TResult>()
                {
                    Result = freshResult,
                };

                Cache[key] = result;
            }

            return result.Result;
        }

        public async Task<TResult> GetOrRequestAsync(TKey key, Func<Task<TResult>> request)
        {
            if (Cache.TryGetValue(key, out var result) && !result.Expired(this.ResultLifeTime))
            {
                // Do nothing, use the cache
            }
            else
            {
                var freshResult = request();
                result = new CachableApiResult<TResult>()
                {
                    Result = await freshResult,
                };

                Cache[key] = result;
            }

            return result.Result;
        }

    }

    public class CachableApiResult<T>
    {

        public T Result { get; set; }
        public DateTime CreatedTime { get; set; } = DateTime.UtcNow;

        public bool Expired(int lifeTimeInSecond)
        {
            return DateTime.UtcNow > this.CreatedTime.AddSeconds(lifeTimeInSecond);
        }

    }
}

LukeVo.Faith.MainWebsite/Models/ErrorViewModel.cs
using System;

namespace LukeVo.Faith.MainWebsite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LukeVo.Faith.MainWebsite/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LukeVo.Faith.MainWebsite.Controllers
{
    public class AppsController : Controller
    {

        [Route("daily-bible-verse")]
        public IActionResult DailyBibleVerse()
        {
            return this.View();
        }

    }
}

LukeVo.Faith.MainWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LukeVo.Faith.MainWebsite.Models;
using LukeVo.Faith.MainWebsite.Models.BibleGatewayApi;

namespace LukeVo.Faith.MainWebsite.Controllers
{
    public class HomeController : Controller
    {

        [Route("")]
        public async Task<IActionResult> Index()
        {
            var service = this.HttpContext.RequestServices.GetService(typeof(BibleGatewayConnector)) as BibleGatewayConnector;
            var model = await service.GetVotDAsync("NIV");

            return this.View(model.votd);
        }
        
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LukeVo.Faith.MainWebsite/Views/Apps/DailyBibleVerse.cshtml
@{
    this.ViewBag.Title = "Daily Bible Verse - LukeVo.Faith";
}

LukeVo.Faith.MainWebsite/Views/Home/Index.cshtml
@model VotD

@{
    this.ViewBag.Title = "LukeVo.Faith";
}

<div class="container">
    <div class="votd h-100">
        <p class="votd-text">@this.Html.Raw(this.Model.text)</p>
    </div>

</div>

LukeVo.Faith.MainWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@(this.ViewBag.Title)</title>

    <environment include="Development">
        <link async rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    </environment>
    <environment exclude="Development">
        <link async rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    </environment>

    <link async rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    @this.RenderSection("Heads", required: false)
</head>
<body>
    <header id="section-header" class="header">
        <div class="container">
            <div class="d-flex align-items-center">
                <h2 class="logo">
                    <a asp-controller="Home" asp-action="Index">
                        LukeVo.Faith
                    </a>
                </h2>

                <div class="links">
                    <a asp-controller="Apps" asp-action="DailyBibleVerse">
                        Daily Bible Verse
                    </a>
                    <a href="//dailybibleverse.lukevo.faith">
                        Hymns
                    </a>
                </div>
            </div>

        </div>
    </header>

    <section id="section-content" class="page-content">
        @this.RenderBody()
    </section>

    <footer id="section-footer" class="footer"></footer>

    <environment include="Development">
        <script defer src="~/lib/jquery/dist/jquery.js"></script>
        <script defer src="~/lib/jquery/dist/jquery.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script defer src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" crossorigin="anonymous"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>